# Generated by Django 3.1.7 on 2021-03-03 08:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('uid', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('uid', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('owner', models.CharField(max_length=200)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insurer.insurer')),
            ],
        ),
        migrations.CreateModel(
            name='RiskField',
            fields=[
                ('uid', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('field_name', models.CharField(max_length=50)),
                ('field_type', models.CharField(choices=[('number', 'number'), ('text', 'text'), ('date', 'date'), ('enum', 'enum')], max_length=10)),
                ('value', models.CharField(max_length=1000)),
                ('description', models.TextField(default='')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insurer.risk')),
            ],
        ),
        migrations.CreateModel(
            name='RiskValueOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('risk_field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insurer.riskfield')),
            ],
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('uid', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('risk_name', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insurer.insurer')),
            ],
        ),
        migrations.AddField(
            model_name='riskfield',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insurer.risktype'),
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insurer.risktype'),
        ),
    ]
