# Generated by Django 3.1.7 on 2021-03-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0002_risktype_insurer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskfield',
            name='risk',
        ),
        migrations.AlterField(
            model_name='risktype',
            name='insurer_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
