# Generated by Django 3.1.7 on 2021-03-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0004_remove_riskfield_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfield',
            name='enum_constants',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.DeleteModel(
            name='RiskValueOptions',
        ),
    ]
