# Generated by Django 3.1.7 on 2021-03-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0005_auto_20210303_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskfield',
            name='enum_constants',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='riskfield',
            name='risk_type',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Risk',
        ),
    ]
