# Generated by Django 3.1.7 on 2021-03-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0006_auto_20210303_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='risktype',
            name='risk_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
