# Generated by Django 3.1.7 on 2021-03-03 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0007_risktype_risk_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risktype',
            name='risk_type',
        ),
    ]
