# Generated by Django 3.1.7 on 2021-03-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0008_remove_risktype_risk_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskfield',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='risktype',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
